apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-konvertering-til-pdf
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nais.io/run-as-user: "1001"
spec:
  image: {{image}}
  port: 3000
  accessPolicy:
    inbound:
      rules:
        - application: sosialhjelp-soknad-api-mock
          cluster: dev-gcp
  ingresses:
    - "https://konvertering-til-pdf.intern.dev.nav.no/"
