apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-konvertering-til-pdf
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nais.io/run-as-user: "1001"
spec:
  image: ghcr.io/navikt/sosialhjelp-konvertering-til-pdf/gotenberg:8.0.0
  command:
    - "gotenberg"
    - "--api-disable-health-check-logging"
    - "--libreoffice-auto-start"
    - "--webhook-disable"
  port: 3000
  liveness:
    path: /health
    initialDelay: 60
    timeout: 5
    failureThreshold: 10
  accessPolicy:
    inbound:
      rules:
        - application: sosialhjelp-soknad-api-mock
          cluster: dev-gcp
        - application: sosialhjelp-avtaler-api-dev
        - application: sosialhjelp-soknad-api
  ingresses:
    - "https://konvertering-til-pdf.intern.dev.nav.no/"
  replicas:
    min: 1
    max: 4
  resources:
    # for lite ressurser allokert kan føre til 503: Service Unavailable fra applikasjonen skjedde med cpu: 200m / mem: 500Mi
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
