apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-konvertering-til-pdf
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nais.io/run-as-user: "1001"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /health
    #port: 3000
    initialDelay: 60
    timeout: 5
    failureThreshold: 10
  #readiness:
    #path: /hea
    #initialDelay: 60
    #timeout: 5
    #port: 3000
  accessPolicy:
    inbound:
      rules:
        - application: sosialhjelp-soknad-api-mock
          cluster: dev-gcp
  ingresses:
    - "https://konvertering-til-pdf.intern.dev.nav.no/"
  replicas:
    min: 2
    max: 4
  resources:
    # for lite ressurser allokert kan føre til 503: Service Unavailable fra applikasjonen skjedde med cpu: 200m / mem: 500Mi
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
