apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-konvertering-til-pdf
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nais.io/run-as-user: "1001"
spec:
  image: ghcr.io/navikt/sosialhjelp-konvertering-til-pdf/gotenberg:8.0.0
  command:
    - "gotenberg"
    - "--api-disable-health-check-logging"
    - "--libreoffice-auto-start"
    - "--webhook-disable"
  port: 3000
  liveness:
    path: /health
    initialDelay: 60
    timeout: 5
    failureThreshold: 10
  accessPolicy:
    inbound:
      rules:
        - application: sosialhjelp-soknad-api
          cluster: prod-fss
  ingresses:
    - "https://konvertering-til-pdf.intern.nav.no/"
    - "https://konvertering-til-pdf.prod-fss-pub.nais.io"
  replicas:
    min: 1
    max: 4
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 2m
      memory: 256Mi
