name: Deploy to prod-fss

on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to NAIS"
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: nais/prod-fss.yaml
          REF: ${{ github.sha }}
