name: Deploy to prod

on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to NAIS"
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        name: "Deploy til prod-gcp"
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/prod-gcp.yaml
          REF: ${{ github.sha }}
