name: Deploy to dev-gcp

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
#  build:
#    name: "Build and push Docker image"
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      id-token: write
#    outputs:
#      image-name: ${{ steps.docker-build-push.outputs.image }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: "Push docker image to GAR"
#        uses: nais/docker-build-push@v0
#        id: docker-build-push
#        with:
#          team: teamdigisos
#          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
#          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy:
    name: "Deploy to NAIS"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-gcp.yaml
          REF: ${{ github.sha }}
