name: Deploy to dev-gcp

on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to NAIS"
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        name: "Deploy til dev-gcp"
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-gcp.yaml
          REF: ${{ github.sha }}
